### ISSUE TITLE
Static content doesn't load in deployed JAR

### ISSUE THREAD

**Issue by kebrahim** [ny/maslow#125]
I deployed a JAR file using the `./mvnw package` command & the static content stored in client/public/ (images, translations, etc) doesn't load.

![yNCqMi67BzF](https://user-images.githubusercontent.com/2208244/88417808-979fec80-cdb0-11ea-9af1-6e5e7fe7ec96.png)

**Comment by marcja** [comment]
The underlying issue is that the urlrewrite rules were never tested and don't work. I'm working on updating the rules. May require changing the client-side routes to have a prefix (for example, `/summary` may become `/app/summary`).
