### ISSUE TITLE
Render integer questions

### ISSUE THREAD

**Issue by tariqajyusuf** [ny/maslow#16]
Questions involving integers (e.g. "What is your annual income?") should have:

- [x] The question title
- [x] A question hint
- [x] A textbox with integer validation
- [x] Validation and error text logic to require non-negative integers (>=0)
- [x] Use HTML5 validation to use numeric keypad
- [x] Testing

**Comment by kebrahim** [comment]
tests should include (from #72 ):
- check that validation is flagged for invalid input
- check hint displayed and not displayed (if exists or not)
- check that the right actions are dispatched to the state
