### ISSUE TITLE
Dynamic i18n content backend

### ISSUE THREAD

**Issue by itssumertime** [ny/maslow#24]
For the Questions and Services content (currently referred to as "dynamic" content), load in the chosen language as opposed to fetching all languages.

- [ ] Create REST controller for locales at <host>/api/explore/v1/locales/{lng}/{ns}. The controller transforms catalog translations into a json map.
- [ ] Configure i18next.js to use [i18next-chained-backend](https://github.com/i18next/i18next-chained-backend) to additional [i18next-http-backend](https://github.com/i18next/i18next-http-backend).

**Comment by marcja** [comment]
Still need to add support for i18next-chained-backend.
