### ISSUE TITLE
Simplify schema for dynamic i18n content backend

### ISSUE THREAD

**Issue by itssumertime** [ny/maslow#25]
To have separate files for each language, we can configure spring.config.additional-location for a wildcard location in classpath (such as “classpath:locales/*/”) and create an application.yaml in each locale directory. The important wrinkle here is that Spring can only merge maps, not lists, so the current catalog schema will need to be modified to support this merging (for example, questions and services are currently lists). However, since questions are strictly ordered, we would need to add a level of indirection to the schema, creating an unordered map of question data plus a new array of question keys to define the question order. Note as well that this would mean that adding a new question or service would typically require editing eight files across eight directories, but it also means that a translator for a specific language would only have to look at one file.

**Comment by marcja** [comment]
With #28, I've updated the schema to represent what we think is pretty close to the final schema (as viewed from the perspective of the client). I will do the work of breaking up `application.yaml` into separate language files in a follow-up PR. Before I get to that, though, I'm going to work on #24.
