### ISSUE TITLE
Implement visual styles to match NYS theme

### ISSUE THREAD

**Issue by mscharfstein** [ny/maslow#69]
Colors, fonts, spacing

**Comment by kebrahim** [comment]
implement Semantic theme

**Comment by kebrahim** [comment]
http://react.semantic-ui.com/theming

**Comment by marcja** [comment]
Matching the NYS theme is definitely at risk for Sprint 1.

**Comment by marcja** [comment]
Forked this into smaller issues:
- #150 
- #151 
- #152 
- #153 
- #154 

Closing this issue.
