### ISSUE TITLE
Add tests for Frontend Components

### ISSUE THREAD

**Issue by mscharfstein** [ny/maslow#72]
- BooleanQuestion:
          - check hint displayed and not displayed (if exists or not)
          - check that the right actions are dispatched to the state           
- NumberQuestion:
          - check that validation is flagged for invalid input
          - check hint displayed and not displayed (if exists or not)
          - check that the right actions are dispatched to the state
- LanguageSwitcher: doesn't need tests
- QuestionForm:
          - submit button works properly (mock "history")
          - check that nothing displays if sections/questions are empty (useSelector mocked to mock return values for form, sections, questions)
          - check that the right number of sections are displayed
          - check that the right number of questions per section are displayed (this will move to the Sections component testing once Sections is built)
- SummaryPage:
          - back button works properly
          - right number of `<p>s` are displayed given the "responses" variable (useSelector is mocked)

Tasks:
- [ ] BooleanQuestion
- [ ] NumberQuestion
- [ ] QuestionForm
- [ ] SummaryPage

**Comment by kebrahim** [comment]
thanks for writing this up. i've already started a PR on QuestionForm, so i can take that one.

**Comment by kebrahim** [comment]
moved all tests to individual component issues
