### ISSUE TITLE
Design the structure of the Redux store

### ISSUE THREAD

**Issue by mscharfstein** [ny/maslow#9]
Design the structure of the Redux store:
- Includes the different slices of reducer logic/actions for the Redux state (in our case, probably TWO slices: one with the questions (populated on initial load), and one with all the answers)
- The slices have reducers, which can have different functions / actions that update the state (in our case, for the answers reducer, probably just an "answerSelected" action (maybe separate for boolean and numeric answers))
- Make sure to export the reducers
- Assumption: Components can look up individually the questions based on their IDs

Reducer for answers can look similar to:

```
const answersSlice = createSlice({
  name: 'answers',
  initialState,
  reducers: {
   answerSelected(state, action) {
      // define the structure of `action.payload`
      // should support both boolean & numeric answers (separate reducers, maybe?)
      // must also have an identifier to lookup and modify only the corresponding
      // question
    }
  }
})
```

Separate reducer slice for questions.

Notes:
- Consider first submitting a PR to create the redux state with an initial state before working on the reducer(s) - this will unblock Issue #10, Issue #12 
- After unblocking the other issues, implement the reducer(s)

**Comment by kebrahim** [comment]
this should also include slices for the form, sections & services data from the API. see https://github.com/ny/maslow/blob/master/server/src/main/resources/application.yaml
